/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BikeInsuranceRouteImport } from './routes/bike-insurance'
import { Route as CarInsuranceRouteImport } from './routes/car-insurance'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FamilyFloaterHealthInsuranceRouteImport } from './routes/family-floater-health-insurance'
import { Route as MaternityNewbornInsuranceRouteImport } from './routes/maternity-newborn-insurance'
import { Route as PersonalLoanRouteImport } from './routes/personal-loan'
import { Route as SeniorCitizenHealthInsuranceRouteImport } from './routes/senior-citizen-health-insurance'
import { Route as StarHealthInsuranceRouteImport } from './routes/star-health-insurance'
import { Route as TermLifeInsuranceRouteImport } from './routes/term-life-insurance'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BikeInsuranceRoute = BikeInsuranceRouteImport.update({
  id: '/bike-insurance',
  path: '/bike-insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const CarInsuranceRoute = CarInsuranceRouteImport.update({
  id: '/car-insurance',
  path: '/car-insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyFloaterHealthInsuranceRoute =
  FamilyFloaterHealthInsuranceRouteImport.update({
    id: '/family-floater-health-insurance',
    path: '/family-floater-health-insurance',
    getParentRoute: () => rootRouteImport,
  } as any)
const MaternityNewbornInsuranceRoute =
  MaternityNewbornInsuranceRouteImport.update({
    id: '/maternity-newborn-insurance',
    path: '/maternity-newborn-insurance',
    getParentRoute: () => rootRouteImport,
  } as any)
const PersonalLoanRoute = PersonalLoanRouteImport.update({
  id: '/personal-loan',
  path: '/personal-loan',
  getParentRoute: () => rootRouteImport,
} as any)
const SeniorCitizenHealthInsuranceRoute =
  SeniorCitizenHealthInsuranceRouteImport.update({
    id: '/senior-citizen-health-insurance',
    path: '/senior-citizen-health-insurance',
    getParentRoute: () => rootRouteImport,
  } as any)
const StarHealthInsuranceRoute = StarHealthInsuranceRouteImport.update({
  id: '/star-health-insurance',
  path: '/star-health-insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const TermLifeInsuranceRoute = TermLifeInsuranceRouteImport.update({
  id: '/term-life-insurance',
  path: '/term-life-insurance',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bike-insurance': typeof BikeInsuranceRoute
  '/car-insurance': typeof CarInsuranceRoute
  '/contact': typeof ContactRoute
  '/family-floater-health-insurance': typeof FamilyFloaterHealthInsuranceRoute
  '/maternity-newborn-insurance': typeof MaternityNewbornInsuranceRoute
  '/personal-loan': typeof PersonalLoanRoute
  '/senior-citizen-health-insurance': typeof SeniorCitizenHealthInsuranceRoute
  '/star-health-insurance': typeof StarHealthInsuranceRoute
  '/term-life-insurance': typeof TermLifeInsuranceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bike-insurance': typeof BikeInsuranceRoute
  '/car-insurance': typeof CarInsuranceRoute
  '/contact': typeof ContactRoute
  '/family-floater-health-insurance': typeof FamilyFloaterHealthInsuranceRoute
  '/maternity-newborn-insurance': typeof MaternityNewbornInsuranceRoute
  '/personal-loan': typeof PersonalLoanRoute
  '/senior-citizen-health-insurance': typeof SeniorCitizenHealthInsuranceRoute
  '/star-health-insurance': typeof StarHealthInsuranceRoute
  '/term-life-insurance': typeof TermLifeInsuranceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bike-insurance': typeof BikeInsuranceRoute
  '/car-insurance': typeof CarInsuranceRoute
  '/contact': typeof ContactRoute
  '/family-floater-health-insurance': typeof FamilyFloaterHealthInsuranceRoute
  '/maternity-newborn-insurance': typeof MaternityNewbornInsuranceRoute
  '/personal-loan': typeof PersonalLoanRoute
  '/senior-citizen-health-insurance': typeof SeniorCitizenHealthInsuranceRoute
  '/star-health-insurance': typeof StarHealthInsuranceRoute
  '/term-life-insurance': typeof TermLifeInsuranceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bike-insurance'
    | '/car-insurance'
    | '/contact'
    | '/family-floater-health-insurance'
    | '/maternity-newborn-insurance'
    | '/personal-loan'
    | '/senior-citizen-health-insurance'
    | '/star-health-insurance'
    | '/term-life-insurance'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bike-insurance'
    | '/car-insurance'
    | '/contact'
    | '/family-floater-health-insurance'
    | '/maternity-newborn-insurance'
    | '/personal-loan'
    | '/senior-citizen-health-insurance'
    | '/star-health-insurance'
    | '/term-life-insurance'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bike-insurance'
    | '/car-insurance'
    | '/contact'
    | '/family-floater-health-insurance'
    | '/maternity-newborn-insurance'
    | '/personal-loan'
    | '/senior-citizen-health-insurance'
    | '/star-health-insurance'
    | '/term-life-insurance'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BikeInsuranceRoute: typeof BikeInsuranceRoute
  CarInsuranceRoute: typeof CarInsuranceRoute
  ContactRoute: typeof ContactRoute
  FamilyFloaterHealthInsuranceRoute: typeof FamilyFloaterHealthInsuranceRoute
  MaternityNewbornInsuranceRoute: typeof MaternityNewbornInsuranceRoute
  PersonalLoanRoute: typeof PersonalLoanRoute
  SeniorCitizenHealthInsuranceRoute: typeof SeniorCitizenHealthInsuranceRoute
  StarHealthInsuranceRoute: typeof StarHealthInsuranceRoute
  TermLifeInsuranceRoute: typeof TermLifeInsuranceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bike-insurance': {
      id: '/bike-insurance'
      path: '/bike-insurance'
      fullPath: '/bike-insurance'
      preLoaderRoute: typeof BikeInsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/car-insurance': {
      id: '/car-insurance'
      path: '/car-insurance'
      fullPath: '/car-insurance'
      preLoaderRoute: typeof CarInsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family-floater-health-insurance': {
      id: '/family-floater-health-insurance'
      path: '/family-floater-health-insurance'
      fullPath: '/family-floater-health-insurance'
      preLoaderRoute: typeof FamilyFloaterHealthInsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maternity-newborn-insurance': {
      id: '/maternity-newborn-insurance'
      path: '/maternity-newborn-insurance'
      fullPath: '/maternity-newborn-insurance'
      preLoaderRoute: typeof MaternityNewbornInsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal-loan': {
      id: '/personal-loan'
      path: '/personal-loan'
      fullPath: '/personal-loan'
      preLoaderRoute: typeof PersonalLoanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/senior-citizen-health-insurance': {
      id: '/senior-citizen-health-insurance'
      path: '/senior-citizen-health-insurance'
      fullPath: '/senior-citizen-health-insurance'
      preLoaderRoute: typeof SeniorCitizenHealthInsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/star-health-insurance': {
      id: '/star-health-insurance'
      path: '/star-health-insurance'
      fullPath: '/star-health-insurance'
      preLoaderRoute: typeof StarHealthInsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/term-life-insurance': {
      id: '/term-life-insurance'
      path: '/term-life-insurance'
      fullPath: '/term-life-insurance'
      preLoaderRoute: typeof TermLifeInsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BikeInsuranceRoute: BikeInsuranceRoute,
  CarInsuranceRoute: CarInsuranceRoute,
  ContactRoute: ContactRoute,
  FamilyFloaterHealthInsuranceRoute: FamilyFloaterHealthInsuranceRoute,
  MaternityNewbornInsuranceRoute: MaternityNewbornInsuranceRoute,
  PersonalLoanRoute: PersonalLoanRoute,
  SeniorCitizenHealthInsuranceRoute: SeniorCitizenHealthInsuranceRoute,
  StarHealthInsuranceRoute: StarHealthInsuranceRoute,
  TermLifeInsuranceRoute: TermLifeInsuranceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
